language: c
before_install:
  - git clone https://github.com/golang/go.git /home/travis/go1.4
  - cd /home/travis/go1.4/src; git checkout release-branch.go1.4
  - ./make.bash
script:
  - cd $TRAVIS_BUILD_DIR/src; GOARCH=amd64 GOOS=harvey ./bootstrap.bash
